### ISSUE TITLE
LINQ: Roadmap

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Starcounter.Linq#6]
This represents the Roadmap for all fixes, new functionalities and enhancements related to Starcounter.Linq library.

### Roadmap

- [x] Version 1.0.0
  - [x] SELECT clause
  - [x] WHERE clause
  - [x] AND/OR operators
  - [x] Comparison operators (`=`, `>`, `>=`, `<`, `<=`, `<>`, `Object.Equals`) - ~#35~
  - [x] LIKE operator
    - [x] Using `String.Contains` method
    - [x] Using `String.StartsWith` method
    - [x] Using `String.EndsWith` method
  - [x] NOT operator 
  - [x] IS operator (using `is` operator) - ~#13~
  - [x] FETCH clause
    - [x] Using `IQueryable.Take` method
    - [x] Using `IQueryable.FirstOrDefault` method
    - [x] Using `IQueryable.First` method - ~#24~
  - [x] OFFSET clause (using `IQueryable.Skip` method)
  - [x] Support of `IEnumerable.Contains` method in predicates
  - [x] COUNT function
    - [x] Using `IQueryable.Count()` method
    - [x] Using `IQueryable.Count(predicate)` method
  - [x] AVG function
  - [x] MIN function
  - [x] MAX function
  - [x] SUM function
  - [x] ORDER BY clause
  - [x] Support of calculating expression values - ~#14~
  - [x] Implement CompiledQuery - ~#9~
  - [x] Add tests using [xUnit](https://xunit.github.io/) and [Starcounter.Xunit.Runner](https://github.com/Starcounter/Starcounter.Xunit.Runner)
    - [x] SQL building tests
    - [x] Ad-hoc query tests - ~#7~
    - [x] Compiled Query tests - ~#8~
  - [x] Cleanup and refactor the source code - ~#18~
  - [x] NuGet package creating and publishing - ~#18~
  - [x] Fix issues: ~#19~ ~#21~ ~#20~
  - [x] Support First, FirstOrDefault, Single, SingleOrDefault and Any methods - ~#27~
  - [x] README - ~#26~
  - [x] DELETE FROM statement - ~#16~
- [ ] Nice to have
  - [ ] Support IQueryable.All method - #31 
  - [ ] GROUP BY clause
  - [ ] SELECT clause for custom set of fields (using `IQueryable.Select` method)

**Comment by un-tone** [comment]
Currently last version locates in the `literals-fix` branch (PR #5).

cc @rogeralsing @miyconst

**Comment by un-tone** [comment]
Just updated to 0.4.0 version https://www.nuget.org/packages/Starcounter.Linq/0.4.0

**Comment by miyconst** [comment]
Good job @un-tone!

Is the package stable enough to start using it?

The package page shows that you are the package owner, it has to be updated to state that Starcounter owns the package in the next versions.

**Comment by un-tone** [comment]
Yes, I think we should start using it.

I've just added Starcounter as an owner of this package. Should I exclude myself from the owners also?

**Comment by miyconst** [comment]
@un-tone please use git tags to mark releases, and include link to the NuGet package in the release/tag description. 

Other than that the checklist for the version `Version 1.0.0` is completed. I suggest we close this issue.

**Comment by un-tone** [comment]
Closing
